<?xml version="1.0" encoding="utf-8"?><Database Name="RedmineReport" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=5746-WIN7\PENGUIN;Initial Catalog=RedmineReport;Integrated Security=True" SettingsObjectName="Harvester.Properties.Settings" SettingsPropertyName="RedmineConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Repository" Member="Repositories">
    <Type Name="Repository">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Branch" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Feature" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="HarvestFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.AddRepositoryEntry" Method="AddRepositoryEntry">
    <Parameter Name="branch" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="feature" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="mercurialChangesetId" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="user" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="createdDateTime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="summary" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="files" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="branches" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="bookmarks" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="issueNumber" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="AddRepositoryEntryResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>