<?xml version="1.0" encoding="utf-8"?><Database Name="RedmineReport" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=GKIM-V7\PENGUIN;Initial Catalog=RedmineReport;Integrated Security=True" SettingsObjectName="Harvester.Properties.Settings" SettingsPropertyName="RedmineConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Repository" Member="Repositories">
    <Type Name="Repository">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Branch" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Feature" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="HarvestFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Repository_CustomerRepository" Member="CustomerRepositories" ThisKey="Id" OtherKey="Repository" Type="CustomerRepository" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerRepository" Member="CustomerRepositories">
    <Type Name="CustomerRepository">
      <Column Name="Customer" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Repository" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Repository_CustomerRepository" Member="Repository1" ThisKey="Repository" OtherKey="Id" Type="Repository" IsForeignKey="true" />
      <Association Name="Customer_CustomerRepository" Member="Customer1" ThisKey="Customer" OtherKey="Id" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="HarvestFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Customer_CustomerRepository" Member="CustomerRepositories" ThisKey="Id" OtherKey="Customer" Type="CustomerRepository" />
    </Type>
  </Table>
  <Function Name="dbo.AddBookmark" Method="AddBookmark">
    <Parameter Name="branch" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="feature" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="mercurialChangesetId" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="mercurialBookmark" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="AddBookmarkResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AddBranch" Method="AddBranch">
    <Parameter Name="branch" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="feature" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="mercurialChangesetId" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="mercurialBranch" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="AddBranchResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AddChangeset" Method="AddChangeset">
    <Parameter Name="customerCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="repositoryURL" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="branch" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="feature" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="mercurialChangesetId" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="user" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="createdDateTime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="summary" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="files" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="mercurialChangesetBranch" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="issueNumber" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="AddChangesetResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AddRepositoryEntry" Method="AddRepositoryEntry">
    <Parameter Name="customerCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="repositoryURL" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="branch" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="feature" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="mercurialChangesetId" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="user" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="createdDateTime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="summary" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="files" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="branches" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="bookmarks" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="mercurialChangesetBranch" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="issueNumber" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="AddRepositoryEntryResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AddPortal" Method="AddPortal">
    <Parameter Name="mercurialChangesetId" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="portal" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="AddPortalResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>