#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Harvester
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RedmineTest")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DatabaseDataContext() : 
				base(global::Harvester.Properties.Settings.Default.RedmineConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddRepositoryEntry")]
		public ISingleResult<AddRepositoryEntryResult> AddRepositoryEntry([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string customer, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string branch, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string feature, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string mercurialChangesetId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> createdDateTime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string summary, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string files, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string issueNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customer, branch, feature, mercurialChangesetId, user, createdDateTime, summary, files, issueNumber);
			return ((ISingleResult<AddRepositoryEntryResult>)(result.ReturnValue));
		}
	}
	
	public partial class AddRepositoryEntryResult
	{
		
		private int _Column1;
		
		public AddRepositoryEntryResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int NOT NULL")]
		public int Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
